/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game_of_life;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.TestMethodOrder;

//@Tag("core")
@DisplayName("The whole test suite for the game of life")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
//@TestMethodOrder(MethodOrderer.Random.class)
//@TestMethodOrder(MethodOrderer.Alphanumeric.class)
//@TextMethodOrder(CustomOrder.class) //class CustromOrder should implements MethodOrderer interface
public class TestsSuite {
}
